### ISSUE TITLE
Project organization

### ISSUE THREAD

**Issue by tiffanymtang** [joshuaroy873/acms80870_project_palathinkal#1]
- [x] I would suggest moving .ipynb notebooks to its own folder, e.g., `final_project/notebooks`
- [ ] Be sure to create a `dsiplib` python package (and folder) to supplement your final project
- [x] Add package dependencies to create a reproducible environment (e.g., using conda or venv)

**Comment by joshuaroy873** [comment]
Move the .ipyn files to `final_project/notebooks` folder. Added `conda` based environment. Added functions to `/final_project/python`, not `/dsiplib` yet.
