### ISSUE TITLE
Modularizing code

### ISSUE THREAD

**Issue by tiffanymtang** [joshuaroy873/acms80870_project_palathinkal#2]
I noticed several parts of the notebooks which seem to share similar code or code structures. Try keeping your code modular by wrapping these code chunks into re-usable functions (in your `python/` function). For example, your data cleaning steps (merging, fixing particular data entries, dropping duplicates and NAs, etc) can be wrapped into a single function so that you don't have to copy and paste this code again and again. Same goes for much of the plotting code.

I realize that the current notebooks are mostly for exploration, which is completely fine. But keep in mind, for the final writeup, you should have one notebook that includes both the narrative text and all code needed to reproduce your analysis. I think one of the major advantages of a notebook is that it allows the reader to easily read through the entire analysis, including both narrative text and code. If there is a lot of free-hanging code however, this can be difficult to parse and read. In contrast, if the code is wrapped in functions with human-readable names, the reader can read through the code (and notebook) like a narrative.

**Comment by joshuaroy873** [comment]
Code hasn't been modularized yet as there are always small changes I keep adding to these data cleaning steps. I will wrap everything up in the end when I'm sure that no more small changes needs to be added.

**Comment by joshuaroy873** [comment]
Codes have been modularized to a doable extend.

**Comment by joshuaroy873** [comment]
Merged to modularizing_changes branch.
