### ISSUE TITLE
Add functions to `dsiplib` python package

### ISSUE THREAD

**Issue by tiffanymtang** [joshuaroy873/acms80870_project_palathinkal#3]
Some possible functions to add to your `dsiplib` python package include but are certainly not limited to:

- matplotlib wrapper functions
- custom color themes for plotting
- data cleaning functions

I imagine you will want to use these functions for other projects too.

**Comment by joshuaroy873** [comment]
Have added several functions to the `/final_project/python` folder. Not sure if I should duplicate these functions in `/dsiplib` folder too.
